name: Build OpenJML

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        ## Windows jobs fail on some lit tests and sometimes fail even to
        ## setup a work environment (e.g. dotnet installation)
        ##os: [ubuntu-latest]
        ##os: [ubuntu-latest, windows-latest, ubuntu-16.04]
        os: [ubuntu-latest, windows-latest, macos-latest]
        ##os: [ubuntu-latest, macos-latest]

      fail-fast: false
    steps:
    - name: Manually sync certs
      if: runner.os == 'Linux'
      run: cert-sync /etc/ssl/certs/ca-certificates.crt
    - uses: actions/setup-python@v1
    - name: Set up JDK16 
      uses: actions/setup-java@v1
      with:
        java-version: 1.16
    - name: Checkout OpenJML
      run: |
        git clone https://github.com/OpenJML/OpenJML
        git clone https://github.com/OpenJML/Specs
        ( cd OpenJML; git checkout development-module )
        ( cd Specs; git checkout development-module )
        ls
        ls OpenJML
    - name: Build release
      run: |
        ls
        pwd
        make -f OpenJML/OpenJDKModule/Makefile release trial
