name: Create OpenJML Release

on:
  push:
    branches: [ development-module ]
  pull_request:
    branches: [ development-module ]

jobs:
  version: ## Could be any OS
    runs-on: macos-latest

    strategy:
      fail-fast: false
    steps:
    - name: Checkout OpenJML
      run: |
        git clone -development-module --depth 1 https://github.com/OpenJML/OpenJML
    - name: Find current release
      run: |
        cd OpenJML
        export ver=`cat version.txt`
        export tag=`curl --silent --header 'Authorization: token ${{ secrets.GITHUB_TOKEN }}' "https://api.github.com/repos/OpenJML/OpenJML/releases" | grep tag_name | head -1 | sed -e 's/.*: \"//' -e 's/\",//'`
        echo $ver $tag
        test "$ver" = "$tag" && echo Version $ver already exists 
        test "$ver" != "$tag"
    - name: Create new release
      ##if: "$ver" != "$tag"
      run: |
        cd OpenJML
        export ver=`cat version.txt`
        echo Version $ver
        # Create new version
        curl -s -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -d "{\"tag_name\":\"$ver\", \"target_commitish\":\"development-module\", \"name\":\"OpenJML $ver\", \"draft\":true, \"body\":\"Publishing release $ver\"}" "https://api.github.com/repos/OpenJML/OpenJML/releases" 
