name: Create OpenJML Release

on:
  push:
    branches: [ development-module ]
  pull_request:
    branches: [ development-module ]

jobs:
  build: ## Could be any OS
    runs-on: macos-latest

    strategy:
      fail-fast: false
    steps:
    - name: Checkout OpenJML
      run: |
        git clone https://github.com/OpenJML/OpenJML
        cd OpenJML
        git checkout development-module
    - name: Create release
      run: |
        cd OpenJML
        cat version.txt
        export ver=`cat version.txt`
        cd OpenJDKModule/release-temp
        echo VER $ver
        #curl -s -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -d "{\"tag_name\":\"v$ver\", \"target\":\"development-module\", \"name\":\"OpenJML $ver\", \"draft\":true, \"body\":\"Publishing release $ver\"}" "https://api.github.com/repos/OpenJML/OpenJML/releases" > /tmp/post
        #cat /tmp/post
